//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cables_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CablesEntities : DbContext
    {
        public CablesEntities()
            : base("name=CablesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Current> Current { get; set; }
        public virtual DbSet<Loses> Loses { get; set; }
        public virtual DbSet<Resistance> Resistance { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ThermalResistance> ThermalResistance { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<XResistanceScreen> XResistanceScreen { get; set; }
    }
}
