//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cables_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Current
    {
        public int current_id { get; set; }
        public Nullable<int> cable_id { get; set; }
        public Nullable<int> cross_area { get; set; }
        public Nullable<int> screen_area { get; set; }
        public string material { get; set; }
        public Nullable<int> Voltage { get; set; }
        public string enviroment { get; set; }
        public string paving_type { get; set; }
        public Nullable<int> vein_number { get; set; }
        public Nullable<double> I { get; set; }
        public Nullable<double> Wa { get; set; }
    
        public virtual Resistance Resistance { get; set; }
    }
}
