//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cables_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loses
    {
        public int loses_id { get; set; }
        public Nullable<int> cable_id { get; set; }
        public Nullable<int> cross_area { get; set; }
        public Nullable<int> screen_area { get; set; }
        public string material { get; set; }
        public string enviroment { get; set; }
        public string paving_type { get; set; }
        public Nullable<int> vein_number { get; set; }
        public Nullable<double> Rs { get; set; }
        public Nullable<double> Rs0 { get; set; }
        public Nullable<double> Rs_R { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> Q { get; set; }
        public Nullable<double> Rs_X { get; set; }
        public Nullable<double> LambdaScreen { get; set; }
        public Nullable<double> LambdaArmor { get; set; }
        public Nullable<double> dvn { get; set; }
        public Nullable<double> Fst { get; set; }
        public string Armor { get; set; }
    
        public virtual Resistance Resistance { get; set; }
    }
}
