//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cables_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThermalResistance
    {
        public int thermal_id { get; set; }
        public Nullable<int> cable_id { get; set; }
        public Nullable<int> cross_area { get; set; }
        public Nullable<int> screen_area { get; set; }
        public string material { get; set; }
        public string enviroment { get; set; }
        public string paving_type { get; set; }
        public Nullable<int> vein_number { get; set; }
        public Nullable<int> Voltage { get; set; }
        public Nullable<double> h { get; set; }
        public Nullable<double> h1 { get; set; }
        public Nullable<double> dzh { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> h2 { get; set; }
        public Nullable<double> Ds { get; set; }
        public Nullable<double> h3 { get; set; }
        public Nullable<double> dvn { get; set; }
        public Nullable<double> T1 { get; set; }
        public Nullable<double> T2 { get; set; }
        public Nullable<double> T3 { get; set; }
        public Nullable<double> T4 { get; set; }
        public string Shell { get; set; }
        public string Armor { get; set; }
    
        public virtual Resistance Resistance { get; set; }
    }
}
